import Link from 'next/link';
import { PublicHeader, PublicFooter } from '@/components/public-layout';
import { guides, categories, guideUrl } from '@/config/knowledge';
import { localeOf } from '@/lib/domain';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale);
  return { title: locale === 'de' ? 'Robotaxi-Wissen für Taxiunternehmen: Fragen & Ratgeber' : 'Robotaxi guides for taxi businesses', description: locale === 'de' ? 'Antworten zu Robotaxi-Kosten, Zulassung, Anbietern und Flottenbetrieb – mit Quellen und aktuellem Prüfstand.' : 'Answers about robotaxi costs, German approvals, providers and fleet operations, with sources and review dates.', alternates: { canonical: guideUrl(locale), languages: { de: guideUrl('de'), en: guideUrl('en') } } };
}
export default async function Knowledge({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale); const de = locale === 'de';
  return <><PublicHeader locale={locale} /><main id="main" className="container developments-page">
    <section className="news-hero"><div><p className="eyebrow">ROBOTAXI CONNECT · {de ? 'WISSEN FÜR IHREN BETRIEB' : 'KNOWLEDGE FOR YOUR BUSINESS'}</p><h1>{de ? 'Ihre Fragen. Fundierte Antworten.' : 'Your questions. Informed answers.'}</h1><p>{de ? 'Was bedeuten Robotaxis für Taxiunternehmen? Hier finden Sie verständliche Ratgeber zu Technik, Kosten und dem Einsatz in Deutschland – mit Quellen und einer klaren Trennung zwischen Fakten und unserer Einordnung.' : 'What do robotaxis mean for taxi businesses? Explore practical guides to technology, costs and German operations, with sources and a clear distinction between facts and our assessment.'}</p></div><aside className="news-stamp"><p className="eyebrow">{de ? 'VOM ÜBERBLICK ZUR ENTSCHEIDUNG' : 'FROM OVERVIEW TO DECISION'}</p><strong>{de ? 'Erst verstehen. Dann planen.' : 'Understand. Then plan.'}</strong><p>{de ? 'Die Antworten werden im Wochenlauf auf neue Erkenntnisse geprüft. Maßgeblich ist das Prüfdatum am jeweiligen Beitrag.' : 'Answers are included in the weekly research review. Each article shows when it was last checked.'}</p><Link className="text-link" href={`/${locale}/developments`}>{de ? 'Aktuelle Entwicklungen ↗' : 'Latest developments ↗'}</Link></aside></section>
    <h2>{de ? 'Welche Frage beschäftigt Sie?' : 'What would you like to know?'}</h2>
    <nav className="news-jump" aria-label={de ? 'Fragenübersicht' : 'Question index'}>{guides.map(g => <a href={`#${g.slug}`} key={g.slug}>{categories[locale][g.category]}</a>)}</nav>
    <div className="news-grid">{guides.map(g => <article className="news-card" id={g.slug} key={g.slug}><p className="eyebrow">{categories[locale][g.category]}</p><h3><Link href={`/${locale}/wissen/${g.slug}`}>{g[locale].title}</Link></h3><p>{g[locale].answer}</p><div className="news-source"><small>{de ? 'Geprüft am' : 'Reviewed'} <time dateTime={g.reviewed}>{g.reviewed}</time></small><Link className="text-link" href={`/${locale}/wissen/${g.slug}`}>{de ? 'Antwort und Quellen lesen ↗' : 'Read answer and sources ↗'}</Link></div></article>)}</div>
    <section className="news-archive news-section"><div><h2>{de ? 'Ihre Frage fehlt?' : 'Missing a question?'}</h2><p>{de ? 'Schreiben Sie uns, was Sie in Ihrem Betrieb beschäftigt. Wir nehmen relevante Fragen in die Recherche auf.' : 'Tell us what matters to your operation. Relevant questions will inform our research.'}</p></div><div><a href="mailto:info@robotaxi-connect.de">{de ? 'Frage einreichen' : 'Submit a question'} ↗</a><Link href={`/${locale}/legal/imprint`}>{de ? 'Wer hinter Robotaxi Connect steht' : 'About Robotaxi Connect'} ↗</Link></div></section>
  </main><PublicFooter locale={locale} /></>;
}
