import Link from 'next/link';
import { PublicHeader, PublicFooter } from '@/components/public-layout';
import { localeOf } from '@/lib/domain';
import { siteOrigin } from '@/config/knowledge';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale);
  return { title: locale === 'de' ? 'Robotaxis für Taxiunternehmen und Flottenbetreiber' : 'Robotaxis for taxi businesses and fleet operators', description: locale === 'de' ? 'Den Einstieg in autonome Mobilität vorbereiten: kostenloses Firmenprofil, persönlicher Abgleich mit Technologieanbietern und fundiertes Robotaxi-Wissen.' : 'Prepare for autonomous mobility with a free company profile, personal provider matching and practical robotaxi guides.', alternates: { canonical: `${siteOrigin}/${locale}/taxiunternehmen`, languages: { de: `${siteOrigin}/de/taxiunternehmen`, en: `${siteOrigin}/en/taxiunternehmen` } } };
}
export default async function Taxi({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale); const de = locale === 'de';
  return <><PublicHeader locale={locale} /><main id="main" className="container audience-page"><p className="eyebrow">{de ? 'FÜR TAXI- UND FLOTTENUNTERNEHMEN' : 'FOR TAXI AND FLEET BUSINESSES'}</p><h1>{de ? 'Robotaxis für Ihren Betrieb. Mit einem klaren nächsten Schritt.' : 'Robotaxis for your business. A clear next step.'}</h1><p className="audience-intro">{de ? 'Sie möchten sich auf autonome Mobilität vorbereiten? Stellen Sie uns Ihren Betrieb vor. Wir klären Ihren Bedarf und prüfen persönlich, welche Technologieanbieter zu Ihrem Einsatzprofil passen könnten.' : 'Preparing for autonomous mobility? Introduce your business. We discuss your needs and personally assess which technology providers might fit your operations.'}</p><Link className="button primary" href={`/${locale}/register`}>{de ? 'Als Taxiunternehmen registrieren' : 'Register as a taxi business'} ↗</Link><p className="news-video-note">{de ? 'Registrierung und Plattformnutzung sind kostenlos.' : 'Registration and platform use are free.'}</p>
    <div className="news-grid news-section">{(de ? [['Ihr eigenes Firmenprofil','Beschreiben Sie Flotte, Region und Bedarf. Sie sehen ausschließlich Ihre eigenen Angaben und freigegebenen Vorgänge.'],['Persönliche Vermittlung','Wir fragen Sie vor jeder Weitergabe persönlich nach Ihrer Freigabe. Es gibt kein Verzeichnis anderer Unternehmen und keinen direkten Netzwerkzugang.']] : [['Your company profile','Describe your fleet, region and needs. Only your own information and released records are visible to you.'],['Personal introductions','We request your approval personally before each disclosure. There is no directory of other businesses or direct network access.']]).map(([title,text]) => <section className="news-card" key={title}><h2>{title}</h2><p>{text}</p></section>)}</div>
    <section className="guide-answer"><h2>{de ? 'Erst informieren, dann entscheiden.' : 'Understand before you decide.'}</h2><p>{de ? 'Was kostet ein Robotaxi? Welche Zulassung braucht es? Unsere Ratgeber beantworten typische Fragen mit Quellen.' : 'What does a robotaxi cost? Which approvals are needed? Our sourced guides answer common questions.'}</p><Link className="text-link" href={`/${locale}/wissen`}>{de ? 'Wissen & FAQ für Taxiunternehmen' : 'Guides & FAQ for taxi businesses'} ↗</Link></section>
  </main><PublicFooter locale={locale} /></>;
}
