import Link from 'next/link';
import { PublicHeader, PublicFooter } from '@/components/public-layout';
import { ProviderInquiry } from '@/components/provider-inquiry';
import { localeOf } from '@/lib/domain';
import { siteOrigin } from '@/config/knowledge';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale);
  return { title: locale === 'de' ? 'Für Robotaxi-Technologieanbieter: Unternehmen vorstellen' : 'For robotaxi technology providers: introduce your company', description: locale === 'de' ? 'Stellen Sie Robotaxi Connect Ihre Technologie vor. Persönliche Bearbeitung und gezielte Vermittlung mit Freigabe der beteiligten Unternehmen.' : 'Introduce your technology to Robotaxi Connect for personal review and introductions with the companies’ approval.', alternates: { canonical: `${siteOrigin}/${locale}/technologieunternehmen`, languages: { de: `${siteOrigin}/de/technologieunternehmen`, en: `${siteOrigin}/en/technologieunternehmen` } } };
}
export default async function Providers({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale); const de = locale === 'de';
  return <><PublicHeader locale={locale} /><main id="main" className="container audience-page"><p className="eyebrow">{de ? 'FÜR TECHNOLOGIEUNTERNEHMEN' : 'FOR TECHNOLOGY COMPANIES'}</p><h1>{de ? 'Ihre Technologie. Passende Partner im Flottenbetrieb.' : 'Your technology. Relevant fleet partners.'}</h1><p className="audience-intro">{de ? 'Registrieren Sie Ihr Interesse an einer Zusammenarbeit. Wir besprechen Ihre Lösung und geeignete Einsatzmöglichkeiten persönlich mit Ihnen. Konditionen und mögliche Provisionen werden separat vereinbart.' : 'Register your interest in working together. We discuss your solution and suitable use cases personally. Commercial terms and any commissions are agreed separately.'}</p><Link className="button primary" href={`/${locale}/register?type=technology`}>{de ? 'Als Technologieunternehmen registrieren' : 'Register as a technology company'} ↗</Link><p>{de ? 'Mit eigenem Konto verwalten Sie Ihre Firmen- und Kontaktdaten. Alternativ können Sie uns ohne Konto per E-Mail kontaktieren.' : 'Manage company and contact details with your own account, or contact us by email without an account.'}</p><div className="provider-layout"><ProviderInquiry locale={locale} /><aside className="news-stamp"><h2>{de ? 'So geht es weiter' : 'What happens next'}</h2><ol>{(de ? ['Sie senden uns Ihre Unternehmensanfrage per E-Mail.','Wir kontaktieren Sie persönlich und klären Ihr Angebot.','Wir prüfen passende Betriebe intern und fragen diese vor jeder Datenweitergabe um Freigabe.'] : ['Send your company enquiry by email.','We contact you personally to discuss your offering.','We assess potential matches internally and request approval before sharing company information.']).map(x => <li key={x}>{x}</li>)}</ol><p>{de ? 'Die Daten unseres Netzwerks bleiben vertraulich. Technologieanbieter erhalten keinen Plattform- oder Verzeichniszugang.' : 'Our network data remains confidential. Technology providers receive no platform or directory access.'}</p></aside></div></main><PublicFooter locale={locale} /></>;
}
