import Link from 'next/link';
import { AccountForm } from './account-form';
import { logoutAction } from '@/app/actions/auth';
import type { Profile, Locale } from '@/lib/domain';
export function AccountInput({name,label,value='',type='text',required=true,max=200,autoComplete}:{name:string;label:string;value?:string;type?:string;required?:boolean;max?:number;autoComplete?:string}) {
 return <label className="field">{label}<input name={name} type={type} defaultValue={value} required={required} maxLength={max} autoComplete={autoComplete}/></label>;
}
export function AccountSettings({locale,profile,email,pendingEmail,allowDelete=true}:{locale:Locale;profile:Profile;email:string;pendingEmail?:string;allowDelete?:boolean}) {
 const de=locale==='de'; const current=()=> <AccountInput name="current_password" type="password" label={de?'Aktuelles Passwort':'Current password'} max={128} autoComplete="current-password"/>;
 return <div className="account-settings"><p><a className="text-link" href="/api/export">{de?'Eigene Daten herunterladen':'Download your data'} ↗</a></p>
 <section className="account-card"><h2>{de?'Persönliche Kontaktdaten':'Personal contact details'}</h2><AccountForm kind="profile" locale={locale} submit={de?'Kontaktdaten speichern':'Save contact details'}><AccountInput name="first_name" label={de?'Vorname':'First name'} value={profile.first_name}/><AccountInput name="last_name" label={de?'Nachname':'Last name'} value={profile.last_name}/></AccountForm><p><Link href={`/${locale}/${profile.role==='PROVIDER_USER'?'anbieter':'portal/profile'}`}>{de?'Firmenadresse, Telefon und geschäftliche Kontaktdaten bearbeiten':'Edit company address, phone and business contact details'} ↗</Link></p></section>
 <section className="account-card"><h2>{de?'E-Mail-Adresse für die Anmeldung':'Login email address'}</h2><p>{email}</p>{pendingEmail&&<p className="notice">{de?'Bestätigung ausstehend:':'Confirmation pending:'} {pendingEmail}</p>}<AccountForm kind="email" locale={locale} submit={de?'E-Mail-Änderung anfordern':'Request email change'}><AccountInput name="email" type="email" label={de?'Neue E-Mail-Adresse':'New email address'} autoComplete="email"/>{current()}</AccountForm></section>
 <section className="account-card"><h2>{de?'Passwort ändern':'Change password'}</h2><AccountForm kind="password" locale={locale} submit={de?'Passwort ändern':'Change password'}>{current()}<AccountInput name="password" type="password" label={de?'Neues Passwort (mindestens 12 Zeichen)':'New password (at least 12 characters)'} max={128} autoComplete="new-password"/><AccountInput name="confirm_password" type="password" label={de?'Neues Passwort wiederholen':'Repeat new password'} max={128} autoComplete="new-password"/></AccountForm></section>
 <section className="account-card"><h2>{de?'Abmelden':'Sign out'}</h2><p>{de?'Beendet Ihre Sitzung. Ihr Konto bleibt bestehen.':'Ends your session. Your account remains available.'}</p><form action={logoutAction.bind(null,locale)}><button className="button secondary">{de?'Abmelden':'Sign out'}</button></form></section>
 {allowDelete&&<section className="account-card account-danger"><h2>{de?'Konto endgültig löschen':'Permanently delete account'}</h2><p>{de?'Ihr Zugang und Ihr persönliches Profil werden endgültig gelöscht. Sind Sie der letzte Nutzer Ihres Unternehmens, werden auch dessen gespeicherte Plattformdaten und Dateien gelöscht. Bei weiteren Nutzern bleiben die gemeinsamen Unternehmensdaten bestehen. Diese Aktion kann nicht rückgängig gemacht werden.':'Your login and personal profile are permanently deleted. If you are the last user of your company, its stored platform data and files are also deleted. Shared company records remain if there are other users. This cannot be undone.'}</p><p>{de?'Bereits versendete E-Mails bei Empfängern und Sicherungskopien der Dienstleister werden dadurch nicht sofort entfernt.':'Emails already received by third parties and provider backups are not immediately removed by this action.'}</p><AccountForm kind="delete" locale={locale} submit={de?'Konto unwiderruflich löschen':'Permanently delete account'}>{current()}<AccountInput name="delete_word" label={de?'Zur Bestätigung DELETE eingeben':'Type DELETE to confirm'} max={6}/><label className="checkbox"><input type="checkbox" name="confirm_delete" required/><span>{de?'Ich habe die Folgen verstanden und möchte mein Konto endgültig löschen.':'I understand the consequences and want to permanently delete my account.'}</span></label></AccountForm></section>}
 </div>;
}
