import Link from 'next/link';
import { ArrowUpRight, CarFront, Network } from 'lucide-react';
import { localeOf } from '@/lib/domain';
import { siteOrigin } from '@/config/knowledge';
import { PublicHeader, PublicFooter } from '@/components/public-layout';
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale); const de = locale === 'de';
  return { title: de ? 'Robotaxis für Taxiunternehmen – Technologiepartner finden' : 'Robotaxis for taxi businesses – find technology partners', description: de ? 'Robotaxi Connect verbindet Taxi- und Flottenunternehmen persönlich mit Technologieanbietern für autonome Mobilität. Mit Wissen zu Robotaxis, Kosten und Zulassung.' : 'Robotaxi Connect personally connects taxi and fleet businesses with autonomous mobility technology providers. Explore robotaxi guides, costs and approvals.', alternates: { canonical: `${siteOrigin}/${locale}`, languages: { de: `${siteOrigin}/de`, en: `${siteOrigin}/en` } } };
}
export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const locale = localeOf((await params).locale); const de = locale === 'de';
  return <><PublicHeader locale={locale} /><main id="main">
    <section className="container gateway-hero"><p className="eyebrow">ROBOTAXI CONNECT · {de ? 'AUTONOME MOBILITÄT. PERSÖNLICH VERBUNDEN.' : 'AUTONOMOUS MOBILITY. PERSONAL CONNECTIONS.'}</p>
      <h1>{de ? <>Wir verbinden Taxiunternehmen <br />mit der Robotaxi-Technologie.</> : <>Connecting taxi businesses <br />with robotaxi technology.</>}</h1>
      <p className="gateway-intro">{de ? 'Sie möchten Ihren Taxibetrieb auf autonome Mobilität vorbereiten oder bringen die passende Technologie mit? Wir finden mögliche Partner und begleiten den persönlichen Austausch.' : 'Preparing your taxi business for autonomous mobility, or developing the technology that enables it? We identify potential partners and facilitate personal introductions.'}</p>
      <div className="gateway-choices">
        <article><CarFront size={30} strokeWidth={1.4} /><p className="eyebrow">{de ? 'TAXI- & FLOTTENUNTERNEHMEN' : 'TAXI & FLEET BUSINESSES'}</p><h2>{de ? 'Die Zukunft Ihres Betriebs.' : 'The future of your business.'}</h2><p>{de ? 'Bedarf vorstellen, Möglichkeiten verstehen und passende Technologiepartner kennenlernen.' : 'Describe your needs, understand your options and meet relevant technology partners.'}</p><Link className="button primary" href={`/${locale}/register`}>{de ? 'Als Taxiunternehmen registrieren' : 'Register as a taxi business'} <ArrowUpRight size={17} /></Link><Link className="text-link" href={`/${locale}/taxiunternehmen`}>{de ? 'Mehr für Taxiunternehmen' : 'More for taxi businesses'} ↗</Link></article>
        <article><Network size={30} strokeWidth={1.4} /><p className="eyebrow">{de ? 'TECHNOLOGIEUNTERNEHMEN' : 'TECHNOLOGY COMPANIES'}</p><h2>{de ? 'Ihre Lösung im richtigen Umfeld.' : 'The right setting for your solution.'}</h2><p>{de ? 'Technologie vorstellen und mit uns persönlich geeignete Einsatzmöglichkeiten besprechen.' : 'Introduce your technology and discuss suitable applications with us personally.'}</p><Link className="button primary" href={`/${locale}/technologieunternehmen`}>{de ? 'Als Technologieunternehmen registrieren' : 'Register as a technology company'} <ArrowUpRight size={17} /></Link><span className="news-video-note">{de ? 'Eigenes Profil · Persönliche Bearbeitung' : 'Your profile · Personal handling'}</span></article>
      </div><p className="gateway-note">{de ? 'Persönliche Vermittlung · Vertrauliche Unternehmensprofile · Datenweitergabe nur nach Ihrer Freigabe' : 'Personal introductions · Confidential company profiles · Data shared only with your approval'}</p>
    </section>
    <section className="container gateway-knowledge"><div><p className="eyebrow">{de ? 'ORIENTIERUNG FÜR IHREN NÄCHSTEN SCHRITT' : 'INFORMATION FOR YOUR NEXT STEP'}</p><h2>{de ? 'Robotaxis verstehen. Chancen einordnen.' : 'Understand robotaxis. Assess the opportunities.'}</h2></div><div><p>{de ? 'Antworten auf die Fragen, die Taxiunternehmen beschäftigen: Kosten, Zulassung in Deutschland, Anbieter und Vorbereitung des Betriebs.' : 'Answers to the questions taxi businesses face: costs, German approvals, providers and preparing operations.'}</p><Link className="text-link" href={`/${locale}/wissen`}>{de ? 'Wissen & FAQ entdecken' : 'Explore guides & FAQ'} ↗</Link><Link className="text-link" href={`/${locale}/developments`}>{de ? 'Die neuesten Entwicklungen' : 'Latest developments'} ↗</Link></div></section>
    <section className="container gateway-about"><p>{de ? 'Hinter Robotaxi Connect steht Sebastian Neumeier. Wir vermitteln geschäftliche Kontakte – wir verkaufen keine Fahrzeuge und betreiben keine Robotaxis.' : 'Robotaxi Connect is run by Sebastian Neumeier. We facilitate business introductions; we do not sell vehicles or operate robotaxis.'}</p><Link className="text-link" href={`/${locale}/legal/imprint`}>{de ? 'Persönlich kennenlernen' : 'Meet the person behind the platform'} ↗</Link></section>
  </main><PublicFooter locale={locale} /></>;
}
