import type { Locale } from '@/lib/domain';
export const siteOrigin = 'https://www.robotaxi-connect.de';
type Copy = { title: string; answer: string; sections: { title: string; text: string }[]; checklist: string[] };
export type Guide = { slug: string; category: string; reviewed: string; history?: { date: string; de: string; en: string }[]; sources: { label: string; url: string }[]; de: Copy; en: Copy };
const bmv = { label: 'BMV · Automatisiertes und vernetztes Fahren · 27.05.2026', url: 'https://www.bmv.de/SharedDocs/DE/Artikel/StV/Digitalisierung-der-Mobilitaet/automatisiertes-und-vernetztes-fahren.html' };
const tesla = { label: 'Tesla · Cybercab FAQ · undatiert / undated', url: 'https://www.tesla.com/support/robotaxi/cybercab' };
const fsd = { label: 'Tesla · FSD Supervised · undatiert / undated', url: 'https://www.tesla.com/en_ca/support/fsd' };
const duty = { label: '§ 1f StVG · geltender Gesetzestext / legislation', url: 'https://www.gesetze-im-internet.de/stvg/__1f.html' };
export const guides: Guide[] = [
  { slug: 'robotaxi-oder-fahrerassistenz', category: 'basics', reviewed: '2026-09-16', sources: [fsd, bmv],
    de: { title: 'Was ist ein Robotaxi – und was ist nur Fahrerassistenz?', answer: 'Entscheidend ist, wer die Fahraufgabe übernimmt. Bei Fahrerassistenz bleibt ein aufmerksamer Mensch am Steuer nötig. Autonomer Betrieb kann innerhalb festgelegter Bedingungen ohne Fahrer stattfinden.', sections: [
      { title: 'Der Produktname reicht nicht', text: 'Tesla bezeichnet FSD Supervised ausdrücklich als Fahrerassistenz mit aktiver Überwachung. Ein solches System ersetzt keinen Taxifahrer. Videos mit selbstständigen Lenkbewegungen belegen deshalb noch keinen fahrerlosen Betrieb. Quelle: Tesla Support.' },
      { title: 'Was Level 4 für den Betrieb bedeutet', text: 'Der deutsche Rechtsrahmen ermöglicht fahrerlosen Betrieb in festgelegten Betriebsbereichen. Daraus folgt keine Erlaubnis, jedes Fahrzeug auf jeder Strecke einzusetzen. Quelle: BMV. Unsere Einordnung: Fragen Sie nach Betriebsgebiet und Grenzen bei Wetter, Straßen und Störungen.' }], checklist: ['Wer muss während der Fahrt aufpassen?', 'Welche Betriebsbedingungen sind freigegeben?', 'Was passiert, wenn das System seine Grenzen erreicht?'] },
    en: { title: 'What is a robotaxi, and what is driver assistance?', answer: 'The key question is who performs the driving task. Driver assistance still requires an attentive human driver. Autonomous operation can work without a driver within defined conditions.', sections: [
      { title: 'A product name is not enough', text: 'Tesla explicitly describes FSD Supervised as assistance requiring active supervision. It does not replace a taxi driver. Footage of automatic steering therefore does not establish driverless operation. Source: Tesla Support.' },
      { title: 'What Level 4 means for operations', text: 'Germany’s framework permits driverless operation in defined operating areas, rather than every vehicle on every road. Source: BMV. Our assessment: ask about geographic, weather and road limits and how failures are handled.' }], checklist: ['Who must supervise each trip?', 'Which operating conditions are approved?', 'What happens at system limits?'] } },
  { slug: 'robotaxi-zulassung-deutschland', category: 'approval', reviewed: '2026-09-16', sources: [bmv, { label: '§ 2 PBefG · Genehmigungspflicht / permit requirements', url: 'https://www.gesetze-im-internet.de/pbefg/__2.html' }],
    de: { title: 'Darf mein Taxiunternehmen Robotaxis in Deutschland einsetzen?', answer: 'Grundsätzlich gibt es einen Rechtsrahmen für fahrerlosen Betrieb. Ob Ihr konkretes Vorhaben zulässig ist, hängt von Fahrzeug, Betriebsbereich und Beförderungsangebot ab. Ein Fahrzeugkauf allein genügt nicht.', sections: [
      { title: 'Fahrzeug und Einsatzgebiet getrennt prüfen', text: 'Das BMV nennt das KBA für die nationale Fahrzeuggenehmigung. Festgelegte Betriebsbereiche genehmigen die zuständigen Stellen der Länder beziehungsweise auf Bundesfernstraßen die Autobahn GmbH. Quelle: BMV.' },
      { title: 'Auch die Personenbeförderung zählt', text: '§ 2 PBefG regelt die Genehmigungspflicht für die dort genannten Beförderungsarten. Klären Sie mit Ihrer Genehmigungsbehörde, welche Erlaubnisse Ihr konkretes Angebot braucht. Eine technische Freigabe ersetzt diese Prüfung nicht. Dieser Überblick ersetzt keine Prüfung des Einzelfalls.' }], checklist: ['Fahrzeugnachweise beim Anbieter anfordern.', 'Betriebsbereich und zuständige Behörde bestimmen.', 'Beförderungskonzept vor einer Investition abstimmen.'] },
    en: { title: 'Can my taxi business operate robotaxis in Germany?', answer: 'Germany has a framework for driverless operation. Your specific project depends on the vehicle, operating area and passenger service. Buying a vehicle is not sufficient.', sections: [
      { title: 'Check the vehicle and area separately', text: 'BMV identifies KBA as the national vehicle approval authority. Designated operating areas are approved by competent state authorities, or Autobahn GmbH on federal trunk roads. Source: BMV.' },
      { title: 'Passenger transport also matters', text: 'Section 2 PBefG sets permit requirements for the transport types it covers. Ask your licensing authority which permissions your service needs. Technical approval does not replace this assessment. This overview is not a review of an individual project.' }], checklist: ['Request vehicle approval documents.', 'Identify the operating area and authority.', 'Discuss the service concept before investing.'] } },
  { slug: 'robotaxi-kosten-wirtschaftlichkeit', category: 'costs', reviewed: '2026-09-16', sources: [tesla, duty],
    de: { title: 'Was kostet ein Robotaxi – und wann lohnt es sich?', answer: 'Eine belastbare Kalkulation braucht ein konkretes Angebot und Ihre Betriebsdaten. Ein beworbener Fahrzeugpreis sagt noch nichts über die Kosten pro bezahltem Kilometer aus.', sections: [
      { title: 'Welche Kosten gehören in die Rechnung?', text: 'Unsere Kalkulationshilfe: Finanzierung oder Leasing, Software und Plattformgebühren, Versicherung, Energie, Ladeplätze, Reinigung, Wartung, technische Betreuung und Ausfallzeiten berücksichtigen. § 1f StVG sieht unter anderem Halterpflichten zur Wartung und technischen Aufsicht vor. Fahrerlos bedeutet daher nicht betreuungsfrei.' },
      { title: 'Mit bezahlten Kilometern rechnen', text: 'Teilen Sie die gesamten monatlichen Betriebskosten durch die bezahlten Kilometer. Beispiel mit frei gewählten Annahmen: 6.000 Euro Kosten und 10.000 bezahlte Kilometer ergeben 0,60 Euro je Kilometer vor Gewinn. Bei nur 5.000 Kilometern sind es 1,20 Euro. Das sind keine Marktpreise oder Renditeprognosen. Teslas FAQ bietet eine gewerbliche Kontaktanfrage, aber keinen verbindlichen deutschen Komplettpreis.' }], checklist: ['Leerkilometer und Standzeiten mitrechnen.', 'Vertragliche Gebühren und Serviceleistungen schriftlich klären.', 'Mit niedriger, mittlerer und hoher Auslastung rechnen.'] },
    en: { title: 'What does a robotaxi cost, and when does it pay off?', answer: 'A reliable calculation needs a specific quote and your operating data. An advertised vehicle price does not establish cost per paid kilometre.', sections: [
      { title: 'Include the full operating cost', text: 'Our planning framework includes financing, software and platform fees, insurance, energy, charging sites, cleaning, maintenance, technical support and downtime. Section 1f StVG includes owner duties concerning maintenance and technical supervision. Driverless does not mean support-free.' },
      { title: 'Calculate against paid kilometres', text: 'Divide total monthly operating costs by paid kilometres. Illustrative assumptions: €6,000 and 10,000 paid kilometres produce €0.60 per kilometre before profit; 5,000 kilometres produce €1.20. These are not market prices or return forecasts. Tesla’s FAQ offers a commercial enquiry, not a binding German all-in price.' }], checklist: ['Include empty mileage and downtime.', 'Get fees and service commitments in writing.', 'Model low, medium and high utilisation.'] } },
  { slug: 'robotaxi-anbieter-auswaehlen', category: 'providers', reviewed: '2026-09-16', sources: [tesla, { label: 'MOIA · ID. Buzz AD · 23.06.2025', url: 'https://www.moia.io/en/blog/autonomous-ridepooling-id-buzz-ad' }],
    de: { title: 'Welche Robotaxi-Anbieter passen zu meinem Taxiunternehmen?', answer: 'Vergleichen Sie das gesamte Betriebskonzept: Fahrzeug, Software, Service, Genehmigungen und Vertragsmodell. Nicht jeder Anbieter verkauft ein Fahrzeug oder unterstützt unabhängige Flotten in Deutschland.', sections: [
      { title: 'Zwei unterschiedliche Ansätze', text: 'Tesla nennt in seiner Cybercab-FAQ zwei Sitzplätze und bietet Interessenten eine gewerbliche Kontaktanfrage. MOIA beschreibt beim ID. Buzz AD vier Plätze sowie ein Angebot aus Fahrzeug, Software und Betriebsunterstützung. Das sind Herstellerangaben, keine Liefer- oder Partnerschaftszusagen für Ihren Standort.' },
      { title: 'Unser Vorschlag für den Vergleich', text: 'Lassen Sie sich Sitzplatzbedarf, Barrierefreiheit, Gepäckkapazität, Servicezeiten und Einsatzgebiet bestätigen. Klären Sie außerdem, wem Kundenzugang und Betriebsdaten gehören und welche Kündigungs- oder Wechselmöglichkeiten bestehen. Aktuelle Meldungen finden Sie zusätzlich in unserem Entwicklungsüberblick.' }], checklist: ['Nachweise statt einer allgemeinen Roadmap verlangen.', 'Service, Ladebedarf und Vertragsbindung vergleichen.', 'Den Anbieter an Ihrem realen Einsatzprofil messen.'] },
    en: { title: 'Which robotaxi providers fit my taxi business?', answer: 'Compare the whole operating model: vehicle, software, service, approvals and contract. Not every provider sells vehicles or supports independent German fleets.', sections: [
      { title: 'Two different approaches', text: 'Tesla’s Cybercab FAQ lists two seats and provides a commercial enquiry route. MOIA describes four seats in the ID. Buzz AD and a combination of vehicle, software and operational support. These supplier statements do not guarantee local deliveries or partnerships.' },
      { title: 'Our comparison framework', text: 'Confirm seating, accessibility, luggage capacity, service hours and operating area. Establish who controls customer access and operational data, and how you can terminate or switch contracts. Our developments overview tracks related announcements.' }], checklist: ['Ask for evidence, not just a roadmap.', 'Compare service, charging and contractual commitments.', 'Match providers to your real operating requirements.'] } },
  { slug: 'taxibetrieb-auf-robotaxis-vorbereiten', category: 'operations', reviewed: '2026-09-16', sources: [duty],
    de: { title: 'Wie bereite ich meinen Taxibetrieb auf Robotaxis vor?', answer: 'Beginnen Sie mit Ihren Einsatzdaten und Betriebsabläufen. Ein klar beschriebenes Einsatzgebiet und eine nachvollziehbare Kostenbasis helfen mehr als eine vorschnelle Fahrzeugbestellung.', sections: [
      { title: 'Was Sie heute zusammentragen können', text: 'Unsere Empfehlung: typische Strecken, Nachfrage nach Tageszeit, bezahlte und unbezahlte Kilometer, Fahrgastanforderungen, Standzeiten und verfügbare Stell- und Ladeplätze erfassen. Arbeiten Sie für erste Anbietergespräche mit zusammengefassten Daten statt personenbezogenen Fahrgastdaten.' },
      { title: 'Menschen bleiben Teil des Betriebs', text: '§ 1f StVG weist Haltern und technischer Aufsicht Aufgaben zu. Für die praktische Planung sollten Sie zusätzlich Zuständigkeiten für Reinigung, Kundenhilfe, Wartung und Störungen festlegen. Ein begrenzter Pilot sollte vorher messbare Ziele bekommen: Verfügbarkeit, Servicequalität und Gesamtkosten. Das ist unsere Planungsempfehlung, keine Zusage eines verfügbaren Pilotprogramms.' }], checklist: ['Ein konkretes Einsatzprofil erstellen.', 'Standort, Personalaufgaben und Infrastruktur prüfen.', 'Pilotziele und Abbruchkriterien vorab festlegen.'] },
    en: { title: 'How can I prepare my taxi business for robotaxis?', answer: 'Start with operating data and workflows. A clear service area and cost baseline are more useful than an early vehicle order.', sections: [
      { title: 'Information to gather now', text: 'Our recommendation: collect typical routes, demand by time, paid and empty mileage, passenger needs, downtime and parking and charging capacity. Use aggregated figures rather than personal passenger data for initial provider discussions.' },
      { title: 'People remain part of operations', text: 'Section 1f StVG assigns duties to owners and technical supervisors. In practice, also define responsibilities for cleaning, customer support, maintenance and incidents. Set measurable availability, service and cost targets before a limited pilot. This is our planning advice, not a promise of an available pilot programme.' }], checklist: ['Define a specific service profile.', 'Assess the site, people and infrastructure.', 'Agree pilot targets and stopping criteria.'] } },
];
export const categories: Record<Locale, Record<string, string>> = {
  de: { basics: 'Grundlagen', approval: 'Deutschland & Zulassung', costs: 'Kosten', providers: 'Anbieter', operations: 'Betrieb' },
  en: { basics: 'Basics', approval: 'Germany & approvals', costs: 'Costs', providers: 'Providers', operations: 'Operations' },
};
export const guideUrl = (locale: string, slug = '') => `${siteOrigin}/${locale}/wissen${slug ? `/${slug}` : ''}`;
