export const providerQuestions = [
 { key: 'use_cases', de: 'Wie können Taxi- und Mietwagenunternehmen Ihre Technologie einsetzen?', en: 'How can taxi and private-hire operators use your technology?' },
 { key: 'vehicles', de: 'Welche Fahrzeugplattformen werden heute tatsächlich unterstützt? Bitte unterscheiden Sie verfügbare und geplante Plattformen.', en: 'Which vehicle platforms are actually supported today? Please distinguish available and planned platforms.' },
 { key: 'requirements', de: 'Welche Infrastruktur benötigt ein Depot (Laden, Stellplätze, Wartung, Verbindungstechnik)?', en: 'What depot infrastructure is required (charging, parking, maintenance, connectivity)?' },
 { key: 'training_support', de: 'Welche Schulungen und laufende Betreuung sind erforderlich? Welche Leistungen übernehmen Sie?', en: 'What training and ongoing support are required? Which services do you provide?' },
 { key: 'availability_approvals', de: 'Welche Genehmigungen bestehen bereits in Deutschland: Erprobung oder Regelbetrieb? Für welche Fahrzeuge und Gebiete gelten sie, und ab wann ist ein Einsatz möglich?', en: 'Which German approvals are already in place: testing or regular operations? For which vehicles and areas, and when can operations start?' },
 { key: 'partnership', de: 'Suchen Sie externe Betreiber-, Vertriebs- oder Projektpartner in Deutschland? Wie läuft eine Zusammenarbeit ab?', en: 'Are you seeking external operating, sales or project partners in Germany? How does cooperation work?' },
 { key: 'business_model', de: 'Welches Geschäftsmodell bieten Sie in Deutschland an: Fahrzeugverkauf, Leasing, Lizenz für das automatisierte Fahrsystem (ADS), schlüsselfertige Gesamtlösung oder eigener Betrieb?', en: 'Which business model do you offer in Germany: vehicle sales, leasing, automated driving system (ADS) licensing, a turnkey solution or your own operations?' },
 { key: 'odd', de: 'Für welchen Einsatzbereich (ODD) ist der erste deutsche Betrieb vorgesehen? Bitte nennen Sie Straßenarten, Gebiete, Wetterbedingungen, Geschwindigkeiten und weitere Grenzen.', en: 'What operational design domain (ODD) is planned for the first German deployment? Please describe road types, areas, weather, speeds and other limits.' },
 { key: 'supervision', de: 'Wer übernimmt die Technische Aufsicht und wer die Fernunterstützung (Remote Operations)? Bitte Zuständigkeiten getrennt beschreiben.', en: 'Who provides technical supervision and who provides remote operations? Please describe the responsibilities separately.' },
 { key: 'operator_tasks', de: 'Welche Aufgaben verbleiben beim lokalen Betreiber, zum Beispiel Reinigung, Laden, Wartung, Fahrgastbetreuung oder Störungsbehebung?', en: 'Which tasks remain with the local operator, such as cleaning, charging, maintenance, passenger assistance or incident response?' },
 { key: 'minimum_fleet', de: 'Welche Mindestflottengröße ist wirtschaftlich sinnvoll? Unter welchen Annahmen und mit welchen laufenden Kosten?', en: 'What minimum fleet size is commercially viable? Under which assumptions and with what ongoing costs?' },
 { key: 'integration', de: 'Wie integrieren Sie bestehende Taxi- und Ride-Hailing-Apps sowie Dispositionssysteme? Welche Schnittstellen sind heute verfügbar?', en: 'How do you integrate existing taxi and ride-hailing apps and dispatch systems? Which interfaces are available today?' },
] as const;
